In [16]:
import cv2
import numpy as np

In [94]:
img = cv2.imread('1.jpg')
cv2.imshow('1',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 图像模糊： 均值滤波、中值滤波、高斯滤波

图片模糊可用于降低图像噪声；也可用于过滤掉尺寸和亮度较小的物体，使得较大的物体更易于检测

In [132]:
# 在图片中添加 1%的椒盐噪声
row, column, channel = img.shape
noise_salt = np.random.rand(row, column, channel)
percent = 0.01
noise_salt = np.where(noise_salt < percent, 255, 0)

salt = img.astype("float") + noise_salt.astype("float")
salt = np.where(salt > 255, 255, salt)

salt = salt.astype("uint8")
cv2.imshow('img',img)
cv2.imshow('salt',salt)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [133]:
mean_blur = cv2.blur(salt, (3, 3))  # 均值滤波
median_blur = cv2.medianBlur(salt, 3)  # 中值滤波，中值滤波对椒盐噪声具有更好的去噪效果
cv2.imshow('salt',salt)
cv2.imshow('mean_blur',mean_blur)
cv2.imshow('median_blur',median_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

高斯滤波是一种线性平滑滤波，适用于消除高斯噪声

In [134]:
# Gaussian Kernel Effect
g1_img = cv2.GaussianBlur(img, (7, 7), 5)
cv2.imshow('g1',g_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# 高斯卷积核
kernel = cv2.getGaussianKernel(7, 5)   # 7: size, 5: variance
print(kernel)

[[ 0.12895603]
 [ 0.14251846]
 [ 0.15133131]
 [ 0.1543884 ]
 [ 0.15133131]
 [ 0.14251846]
 [ 0.12895603]]


In [116]:
# 二维高斯卷积的计算可分解成 x 方向和 y 方向的两次卷积运算，可以减小运算量
g2_img = cv2.sepFilter2D(img, -1, kernel, kernel)
cv2.imshow('g2_img', g2_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [122]:
# 在图片中添加高斯噪声
mu, sigma = 0, 20  # mu, sigma分布为高斯分布的均值和标准差
noise_img = img + np.random.randn(*img.shape) * sigma + mu  # mu, sigma分布为高斯分布的均值和方差
noise_img[noise_img > 255] = 255
noise_img[noise_img < 0] = 0
noise_img = noise_img.astype("uint8")

cv2.imshow('img',img)
cv2.imshow('noise_img',noise_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [137]:
# 三种滤波方式对高斯噪声的效果
g1_img = cv2.GaussianBlur(noise_img, (3, 3), 2)
mean_blur = cv2.blur(noise_img, (3, 3))  # 均值滤波
median_blur = cv2.medianBlur(noise_img, 3) 
cv2.imshow('noise_img',noise_img)
cv2.imshow('g1',g_img)
cv2.imshow('mean_blur',mean_blur)
cv2.imshow('median_blur',median_blur)

cv2.waitKey(0)
cv2.destroyAllWindows()

# 图像梯度：边缘检测

常用的梯度算子有，通常用于边缘检测、图像增强

In [18]:
# 2nd derivative: laplacian
kernel_lap = np.array([[0,1,0],[1,-4,1],[0,1,0]], np.float32)
print(kernel_lap)

[[ 0.  1.  0.]
 [ 1. -4.  1.]
 [ 0.  1.  0.]]


In [64]:
lap_img = cv2.filter2D(img, -1, kernel = kernel_lap)
cv2.imshow('lap_img', lap_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
img1 = np.random.randint(0, 10, (10,10), np.uint8)
print(img1)
cv2.imshow('1',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[3 1 8 0 7 8 3 3 9 0]
 [6 0 4 0 8 4 9 0 2 1]
 [6 0 7 1 0 9 5 6 5 8]
 [6 4 3 4 9 8 8 8 3 8]
 [0 9 5 9 8 9 6 1 6 5]
 [0 6 1 6 9 8 2 2 2 9]
 [9 9 1 8 7 3 3 4 8 0]
 [1 2 9 0 9 9 3 2 9 6]
 [8 1 1 5 6 6 7 3 6 6]
 [9 5 0 8 8 0 4 1 3 5]]


In [91]:
b = np.array([1,2,4], np.uint8)
a = np.array([3],np.float32)
c = 3.1
print(type(c))


<class 'float'>
